// <auto-generated />
using System;
using FitnessCalculationService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCalculationService.Migrations
{
    [DbContext(typeof(FceDbContext))]
    partial class FceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCalculationService.Domain.Entities.CalculatedMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Bmr")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CalorieTarget")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("Tdee")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CalculatedMetrics");
                });

            modelBuilder.Entity("FitnessCalculationService.Domain.Entities.FitnessPlanConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Goal", "Status")
                        .IsUnique();

                    b.ToTable("FitnessPlanConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A plan designed for LoseWeight with a Weak metabolic rate.",
                            Goal = "LoseWeight",
                            Name = "LoseWeight Plan - Weak",
                            PlanId = "LW-W",
                            Status = "Weak"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A plan designed for LoseWeight with a Normal metabolic rate.",
                            Goal = "LoseWeight",
                            Name = "LoseWeight Plan - Normal",
                            PlanId = "LW-N",
                            Status = "Normal"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A plan designed for LoseWeight with a Hard metabolic rate.",
                            Goal = "LoseWeight",
                            Name = "LoseWeight Plan - Hard",
                            PlanId = "LW-H",
                            Status = "Hard"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A plan designed for GetFitter with a Weak metabolic rate.",
                            Goal = "GetFitter",
                            Name = "GetFitter Plan - Weak",
                            PlanId = "GF-W",
                            Status = "Weak"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A plan designed for GetFitter with a Normal metabolic rate.",
                            Goal = "GetFitter",
                            Name = "GetFitter Plan - Normal",
                            PlanId = "GF-N",
                            Status = "Normal"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A plan designed for GetFitter with a Hard metabolic rate.",
                            Goal = "GetFitter",
                            Name = "GetFitter Plan - Hard",
                            PlanId = "GF-H",
                            Status = "Hard"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A plan designed for GainWeight with a Weak metabolic rate.",
                            Goal = "GainWeight",
                            Name = "GainWeight Plan - Weak",
                            PlanId = "GW-W",
                            Status = "Weak"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A plan designed for GainWeight with a Normal metabolic rate.",
                            Goal = "GainWeight",
                            Name = "GainWeight Plan - Normal",
                            PlanId = "GW-N",
                            Status = "Normal"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A plan designed for GainWeight with a Hard metabolic rate.",
                            Goal = "GainWeight",
                            Name = "GainWeight Plan - Hard",
                            PlanId = "GW-H",
                            Status = "Hard"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A plan designed for GainMoreFlexible with a Weak metabolic rate.",
                            Goal = "GainMoreFlexible",
                            Name = "GainMoreFlexible Plan - Weak",
                            PlanId = "FL-W",
                            Status = "Weak"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A plan designed for GainMoreFlexible with a Normal metabolic rate.",
                            Goal = "GainMoreFlexible",
                            Name = "GainMoreFlexible Plan - Normal",
                            PlanId = "FL-N",
                            Status = "Normal"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A plan designed for GainMoreFlexible with a Hard metabolic rate.",
                            Goal = "GainMoreFlexible",
                            Name = "GainMoreFlexible Plan - Hard",
                            PlanId = "FL-H",
                            Status = "Hard"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A plan designed for LearnTheBasic with a Weak metabolic rate.",
                            Goal = "LearnTheBasic",
                            Name = "LearnTheBasic Plan - Weak",
                            PlanId = "LB-W",
                            Status = "Weak"
                        },
                        new
                        {
                            Id = 14,
                            Description = "A plan designed for LearnTheBasic with a Normal metabolic rate.",
                            Goal = "LearnTheBasic",
                            Name = "LearnTheBasic Plan - Normal",
                            PlanId = "LB-N",
                            Status = "Normal"
                        },
                        new
                        {
                            Id = 15,
                            Description = "A plan designed for LearnTheBasic with a Hard metabolic rate.",
                            Goal = "LearnTheBasic",
                            Name = "LearnTheBasic Plan - Hard",
                            PlanId = "LB-H",
                            Status = "Hard"
                        });
                });

            modelBuilder.Entity("FitnessCalculationService.Domain.Entities.UserAssignedPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FitnessPlanConfigId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FitnessPlanConfigId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("UserAssignedPlans");
                });

            modelBuilder.Entity("FitnessCalculationService.Domain.Entities.UserFitnessStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserFitnessStats");
                });

            modelBuilder.Entity("FitnessCalculationService.Domain.Entities.UserPlanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AssignedAt")
                        .IsDescending(false, true);

                    b.ToTable("UserPlanHistories");
                });

            modelBuilder.Entity("FitnessCalculationService.Domain.Entities.UserAssignedPlan", b =>
                {
                    b.HasOne("FitnessCalculationService.Domain.Entities.FitnessPlanConfig", "FitnessPlanConfig")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("FitnessPlanConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FitnessPlanConfig");
                });

            modelBuilder.Entity("FitnessCalculationService.Domain.Entities.FitnessPlanConfig", b =>
                {
                    b.Navigation("AssignedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
